import Head from 'next/head';
import { Typography } from '@mui/material';
import { useAuthState } from 'react-firebase-hooks/auth';
import { useCollection } from 'react-firebase-hooks/firestore';
import firebase from './firebase/clientApp';

const Home = () => {
  const [user, loading] = useAuthState(firebase.auth());
  // console.log the current user and loading status
  console.log('Loading:', loading, '|', 'Current user:', user);

  const [servants, servantsLoading] = useCollection(
    firebase.firestore().collection('servants'),
    {}
  );

  if (!servantsLoading && servants) {
    servants.docs.map((doc) => console.log(doc.data()));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Typography variant="h2">Hello world!</Typography>
      </main>
    </>
  );
};

export default Home;
